/*-----------------------------------------------------------------
 Sprites. Generated by SpecDraw v1.0   -   
 S. Romero aka NoP / Compiler
 Drawn by Matriax

 This program is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

------------------------------------------------------------------*/
 
#define spr_width 16
#define spr_height 16

char attributes[8] =
 { 0, 1, 2, 3, 4, 5, 6, 7 };
    
char black[2*16] = {
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
 0, 0, 0, 0, 0, 0
};
 
char black_attr[4] = {
 0, 0, 0, 0
};

//char blue[2*16] = {
// 15, 240, 24, 24, 51, 204, 39, 228, 39, 100, 39, 100, 38, 
// 100, 38, 228, 38, 228, 51, 204, 24, 24, 15, 240, 0, 0, 
// 0, 0, 0, 0, 0, 0

char *Grafico;

/*
char joya1[2*16] = {
 63,252, 127,254, 224,  5, 202,179, 208,  9, 197, 91, 210,169, 197, 91,
 210,169, 197, 91, 210,171, 213, 91, 207,243, 224,  7, 85,126, 63,252
};
*/

char joya2[32] = {
 15,240, 49,140, 74, 82, 178, 77, 138, 81, 229,167, 154, 89, 132, 33,
132, 33, 154, 89, 229,167, 138, 81, 178, 77, 74, 82, 49,140, 15,240 
};

/*
char joya3[32] = {
 15,240, 49,140, 76,114, 162,133, 145,  9, 138,177, 197, 67, 253,167, 
226,191, 194,163, 141, 81, 144,137, 163, 69, 76, 50, 49,140, 15,240
};

char joya4[32] = {
 15,240, 49,140, 69,162, 139,209, 217,155, 164,165, 138, 81, 253,191, 
253,191, 138, 81, 165, 37, 217,155, 139,209, 69,162, 49,140, 15,240 
};


char joya5[32] = {
15,240, 51,204, 123,222, 179,205, 164, 37, 138, 81, 245,175, 242, 79, 
 242, 79, 245,175, 138, 81, 164, 37, 179,205, 123,222, 51,204, 15,240 
};
*/

